version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install
      - cd ../backend && npm install
  pre_build:
    commands:
      - echo Running tests...
      - cd frontend && npm test
      - cd ../backend && npm test
  build:
    commands:
      - echo Building frontend...
      - cd frontend && npm run build
      - echo Copying build to S3...
      - aws s3 sync frontend/build s3://${S3_BUCKET}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: backend
